stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the application..."
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - echo "Running tests..."
    - pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."